version: "3.7"
services:
  postgres:
    image: postgres:11
    ports:
      - 5432:5432
    healthcheck:
      test: "pg_isready -U postgres -d postgres"
      interval: 2s
      timeout: 20s
      retries: 10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres